# config/lighthouse/config.yaml - MENGGUNAKAN PRESET MAINNET

# --- Preset ---
PRESET_BASE: "mainnet"  # <-- PERUBAHAN UTAMA

# --- Waktu Genesis (PENTING: Ganti dengan timestamp di masa depan!) ---
# Saat ini adalah 2 Juli 2025, 01:57 WIB. Gunakan nilai setelah ini.
# Contoh untuk 02:05 WIB: 1751483100
MIN_GENESIS_TIME: 1751483100

# --- Konfigurasi Fork ---
GENESIS_FORK_VERSION: "0x00000000"
ALTAIR_FORK_VERSION: "0x01000000"
BELLATRIX_FORK_VERSION: "0x02000000"
CAPELLA_FORK_VERSION: "0x03000000"
DENEB_FORK_VERSION: "0x04000000"
ELECTRA_FORK_VERSION: "0x05000000"

# --- Jadwal Fork Epoch ---
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_EPOCH: 18446744073709551615

# --- Konfigurasi Lainnya (Nilai disesuaikan untuk mainnet) ---
SECONDS_PER_SLOT: 12
SECONDS_PER_ETH1_BLOCK: 14
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 3 # Tetap 3 agar cepat mulai
GENESIS_DELAY: 10
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
ETH1_FOLLOW_DISTANCE: 2048
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
EJECTION_BALANCE: 32000000000 
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 65536

# --- Konfigurasi Execution Layer (Geth) ---
TERMINAL_TOTAL_DIFFICULTY: 0
CHAIN_ID: 1234
DEPOSIT_CHAIN_ID: 1234
DEPOSIT_NETWORK_ID: 1234
DEPOSIT_CONTRACT_ADDRESS: "0x4242424242424242424242424242424242424242"
DEPOSIT_CONTRACT_DEPLOY_BLOCK: 0

# Ganti dengan alamat wallet Anda
GENESIS_ETH1_BALANCE:
  "0x1111111111111111111111111111111111111111": "1000000000000000000000"